---
title: "Marriage Data analysis"
subtitle: "STA304 WEEK 3"
author: 
  - Maggie Zhang
thanks: "Code and data are available at:https://github.com/MaggieZ111119/CityofToronto_Daily_Shelter_Occupancy.Rproj.git"
date: today
date-format: long
abstract: "This paper investigates the occupancy of shelters in Toronto from 2017 to 2020, focusing on capacity and usage across different shelter sectors. By analyzing the data, we explore how shelter demand {exceeded available resources in certain sectors. This research highlights significant challenges faced by the shelter system, providing insights into the strain on resources and potential gaps in support for the homeless population}. These findings are crucial for informing policies and improving resource allocation to better address homelessness in Toronto."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

# Preparation

#Load used libraries
library(tidyverse)
library(ggplot2)
library(dplyr)
library(knitr)


# Read Data(Quarto need data set to be readed in the file)
shelter_data <- read_csv(here::here("~/CityofToronto_Daily_Shelter_Occupancy.Rproj/data/analysis_data/full_shelter_data.csv"), show_col_types = FALSE)
```


# Introduction

Homelessness is a persistent and complex issue in many areas in Canada(@gaetz2010struggle), and Toronto is no exception. As one of Canada’s largest cities, Toronto faces significant challenges in helping homeless people, who are unable to spend on housing largely due to poverty, to meet the necessities of living(@jadidzadeh2018patterns). The city operates a range of shelters that serve various groups, including men, women, youth, and families. The balance between availability and the demand for these services is crucial for both the well-being of individuals experiencing homelessness and the government's efforts to reduce homelessness population. Understanding how shelter occupancy changes over time is essential for identifying gaps in resources and shaping effective policy responses.

This paper focuses on analyzing shelter occupancy data from 2017 to 2020 in City of Toronto. The data which offers a detailed look at the city’s shelter during this time of period is provided on @OpenDataToronto portal. By examining trends in occupancy through the data, we aim to assess how well Toronto's shelters met the demand for space and where shortages may have occurred. By focusing on specific sectors of the shelter system, pinpoint which groups may have been disproportionately affected by resource limitations. 

FINDING! This study addresses a clear gap in the current literature by providing an up-to-date analysis of Toronto's shelter capacity and usage during a time of unprecedented public health and social challenges. ___ NOTICE!!

The remiander of this paper are in presented in sections: @sec-data : Data, @sec-results :Results, and @sec-discussion :Discussion. The data section introduce the dataset used for analysis, expalinin its source and context that shaped its collection.This section thoroughly summarizes the data using visualizations created with ggplot2 (@R-ggplot2) and tables produced with knitr (@R-knitr). Key variables chosen for the analysis, along with the reasoning behind their selection, are explained. The results section presents the findings drawn from the data, highlighting patterns in shelter occupancy and compare to it's availability. Following by the discussion section, which explores the implications of these findings, particularly in relation to resource allocation and policy development, offering insights into how Toronto's shelter system responded to increasing demand.


# Data {#sec-data}
City that has record of offering shleter servise incluede: Toronto, North York, Scarborough, and Etobicoke.



# Results {#sec-results}
This histogram reflects the amount new marriage happens each year from the year of 2011 to 2024 according to @OpenDataToronto.




# Discussion {#sec-discussion}

## First discussion point {#sec-first-point}

from the study, the Marriage number across Toronto is .....

## Second discussion point

[My second point]

## Third discussion point
[My third point]

## Weaknesses and next steps

The study is not finalized, more detailed and careful data examination is needed.


\newpage

\appendix

# Appendix {-}


# References


